import requests
import logging
import json

logger = logging.getLogger(__name__)

class SlackNotifier:
    def __init__(self, webhook_url):
        self.webhook_url = webhook_url

    def send_summary(self, image_name, summary):
        """
        Sends a formatted block message to Slack with the scan summary.
        """
        color = "#36a64f" # Good green
        if summary["critical"] > 0:
            color = "#E01E5A" # Error red
        elif summary["high"] > 0:
            color = "#ECB22E" # Warning orange

        payload = {
            "attachments": [
                {
                    "color": color,
                    "blocks": [
                        {
                            "type": "header",
                            "text": {
                                "type": "plain_text",
                                "text": f"🛡️ Security Scan Report: {image_name}",
                                "emoji": True
                            }
                        },
                        {
                            "type": "section",
                            "fields": [
                                {
                                    "type": "mrkdwn",
                                    "text": f"*Total Vulnerabilities:*\n{summary['total']}"
                                },
                                {
                                    "type": "mrkdwn",
                                    "text": f"*Critical:*\n{summary['critical']}"
                                }
                            ]
                        },
                        {
                            "type": "section",
                            "fields": [
                                {
                                    "type": "mrkdwn",
                                    "text": f"*High:*\n{summary['high']}"
                                },
                                {
                                    "type": "mrkdwn",
                                    "text": f"*Medium:*\n{summary['medium']}"
                                }
                            ]
                        },
                         {
                            "type": "section",
                            "fields": [
                                {
                                    "type": "mrkdwn",
                                    "text": f"*Low:*\n{summary['low']}"
                                },
                                {
                                    "type": "mrkdwn",
                                    "text": f"*Unknown:*\n{summary['unknown']}"
                                }
                            ]
                        },
                        {
                            "type": "context",
                            "elements": [
                                {
                                    "type": "mrkdwn",
                                    "text": "Generated by SecureScan-Orchestrator"
                                }
                            ]
                        }
                    ]
                }
            ]
        }

        try:
            response = requests.post(
                self.webhook_url, 
                json=payload, # requests automatically sets Content-Type: application/json
                headers={'Content-Type': 'application/json'}
            )
            response.raise_for_status()
            logger.info("Slack notification sent successfully.")
        except requests.exceptions.RequestException as e:
            logger.error(f"Failed to send Slack notification: {e}")
            raise
